config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # VERB + URL + CONTROLLER#ACTION

  # get '/', to: 'pages#home' => same as the root request on line 7
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
    # raise
    member = params[:member]

    @teachers = ["Sheila", "Sy", "Caio"]

    if params[:member]
      @teachers = @teachers.select do |teacher|
        member.downcase == teacher.downcase
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp488</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style='background-color: teal'>
      <%= link_to 'Home', root_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Contact', contact_path %>

      <form action="/contact" method="get">
        <input type="text" name="member" value="<%= params[:member] %>" placeholder="Who are you looking for?">
        <input type="submit">
      </form>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h3>About Us</h3>

app/views/pages/contact.html.erb
<h3>Contact us</h3>


<!-- <p>PE TAB</p> -->
<!-- pe + tab => lets you see the ruby code -->
<%#= Time.now %>


<!-- <p>ER TAB</p> -->
<!-- er + tab => no ruby code -->
<%# Time.now %>


<ul>
  <% @teachers.each do |member| %>
    <li><%= member %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h3>Hello world!</h3>